---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - operator-hub.yaml
  - catalog-source.yaml
  - idms-operator.yaml
  - idms-release.yaml
  - itms-generic.yaml
  - itms-release.yaml
  - registry-ca.yaml
  - image-config.yaml
