---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-project.yaml
  - argocd-application.yaml
  - argocd-ssh-known-hosts-cm.yaml
  - ztp-repo.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - gitopsNS.yaml
  - gitopsOperatorGroup.yaml
  - gitopsSubscription.yaml
