---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-wildcard-certificate
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-30"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  commonName: "*.apps.example.com"
  dnsNames:
  - '*.apps.example.com'
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: acme-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: ingress-wildcard-cert
