---
resources:
  - ns.yaml
  - template-values/regional.yaml
  - template-values/hw-types.yaml
  # - cluster-1.yaml

generators:
  - core-baseline.yaml
  - core-overlay.yaml
  - core-upgrade.yaml
  - core-finish.yaml
