---
apiVersion: config.openshift.io/v1
kind: APIServer
metadata:
  name: cluster
  annotations:
    ran.openshift.io/ztp-deploy-wave: "100"
spec:
  servingCerts:
    namedCertificates:
    {{- range .spec.servingCerts.namedCertificates }}
    - names:
{{ .names | toYaml | indent 6 }}
      servingCertificate:
        name: api-server-cert
    {{- end }}
