---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-wildcard-certificate
  namespace: openshift-ingress
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  commonName: "*.apps.example.com"
  dnsNames:
  - "*.apps.example.com"
  isCA: false
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: acme-issuer
  privateKey:
    algorithm: ECDSA
    size: 256
  secretName: ingress-wildcard-cert
