# T-TSC (Telecom Time Slave Clock) with WPC (Westport Channel) configuration
# This profile receives PTP time from an upstream source and redistributes it
# Interface variables:
#   - $iface_timeRx: Receives (Rx) PTP time from upstream source
#   - $iface_FirstPort: First port on the card (used for WPC timing)
apiVersion: ptp.openshift.io/v1
kind: PtpConfig
metadata:
  name: t-tsc
  namespace: openshift-ptp
  annotations:
    ran.openshift.io/ztp-deploy-wave: "10"
spec:
  profile:
  {{- range .spec.profile }}
  - name: t-tsc
    phc2sysOpts: -r -n (?<domainNumber>[0-9]+) -N 8 -R 16 -u 0 -m -s (?<iface_timeRx>[[:alnum:]]+)
    plugins:
      e810:
        enableDefaultConfig: false
        interconnections:
          {{- .plugins.e810.interconnections | toYaml | nindent 10 }}
        settings:
          {{- .plugins.e810.settings | toYaml | nindent 10 }}
        pins:
          # Syntax guide:
          # - The 1st number in each pair must be one of:
          #    0 - Disabled
          #    1 - RX
          #    2 - TX
          # - The 2nd number in each pair must match the channel number
          {{- .plugins.e810.pins | toYaml | nindent 10 }}
    ptp4lConf: |
      # The interface name is hardware-specific
      [(?<iface_timeRx>[[:alnum:]]+)]
      masterOnly 0
      [global]
      #
      # Default Data Set
      #
      twoStepFlag 1
      slaveOnly 0
      priority1 128
      priority2 (?<priority2>[0-9]+)
      domainNumber (?<domainNumber>[0-9]+)
      clockClass 248
      clockAccuracy 0xFE
      offsetScaledLogVariance 0xFFFF
      free_running 0
      freq_est_interval 1
      dscp_event 0
      dscp_general 0
      dataset_comparison G.8275.x
      G.8275.defaultDS.localPriority 128
      #
      # Port Data Set
      #
      logAnnounceInterval -3
      logSyncInterval -4
      logMinDelayReqInterval -4
      logMinPdelayReqInterval -4
      announceReceiptTimeout 3
      syncReceiptTimeout 0
      delayAsymmetry 0
      fault_reset_interval -4
      neighborPropDelayThresh 20000000
      masterOnly 0
      G.8275.portDS.localPriority 128
      #
      # Run time options
      #
      assume_two_step 0
      logging_level 6
      path_trace_enabled 0
      follow_up_info 0
      hybrid_e2e 0
      inhibit_multicast_service 0
      net_sync_monitor 0
      tc_spanning_tree 0
      tx_timestamp_timeout 50
      unicast_listen 0
      unicast_master_table 0
      unicast_req_duration 3600
      use_syslog 1
      verbose 0
      summary_interval 0
      kernel_leap 1
      check_fup_sync 0
      clock_class_threshold 135
      #
      # Servo Options
      #
      pi_proportional_const (?<pi_proportional_const>[0-9.]+)
      pi_integral_const (?<pi_integral_const>[0-9.]+)
      pi_proportional_scale 0.0
      pi_proportional_exponent -0.3
      pi_proportional_norm_max 0.7
      pi_integral_scale 0.0
      pi_integral_exponent 0.4
      pi_integral_norm_max 0.3
      step_threshold 2.0
      first_step_threshold 0.00002
      max_frequency 900000000
      clock_servo pi
      sanity_freq_limit 200000000
      ntpshm_segment 0
      #
      # Transport options
      #
      transportSpecific 0x0
      ptp_dst_mac 01:1B:19:00:00:00
      p2p_dst_mac 01:80:C2:00:00:0E
      udp_ttl 1
      udp6_scope 0x0E
      uds_address /var/run/ptp4l
      #
      # Default interface options
      #
      clock_type OC
      network_transport L2
      delay_mechanism E2E
      time_stamping hardware
      tsproc_mode filter
      delay_filter moving_median
      delay_filter_length 10
      egressLatency 0
      ingressLatency 0
      boundary_clock_jbod 1
      #
      # Clock description
      #
      productDescription ;;
      revisionData ;;
      manufacturerIdentity 00:00:00
      userDescription ;
      timeSource 0xA0
    ptp4lOpts: -2 --summary_interval -4
    ptpSchedulingPolicy: SCHED_FIFO
    ptpSchedulingPriority: 10
    ptpSettings:
      {{- .ptpSettings | toYaml | nindent 6 }}
    ts2phcConf: |
      [global]
      use_syslog  0
      verbose 1
      logging_level 7
      ts2phc.pulsewidth 100000000
      leapfile  /usr/share/zoneinfo/leap-seconds.list
      domainNumber (?<domainNumber>[0-9]+)
      uds_address /var/run/ptp4l.0.socket
      [(?<iface_FirstPort>[[:alnum:]]+)]
      ts2phc.extts_polarity rising
      ts2phc.extts_correction -10
      ts2phc.master 0
    ts2phcOpts: -s generic -a --ts2phc.rh_external_pps 1
  {{- end }}
  recommend:
  {{- range .spec.recommend }}
  - match:
    {{- range .match }}
    - nodeLabel: {{ template "matchNodeSelectorValue" (list .nodeLabel "node-role.kubernetes.io" ) }}
    {{- end }}
    priority: 4
    profile: t-tsc
  {{- end }}
