---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - acmNS.yaml
  - acmOperGroup.yaml
  - acmSubscription.yaml
  - acmMCH.yaml
  - acmAgentServiceConfig.yaml
  - acmMirrorRegistryCM.yaml
  - acmPerfSearch.yaml
  - acmProvisioning.yaml
  - observabilityNS.yaml
  - observabilityOBC.yaml
  - thanosSecret.yaml
#  - observabilitySecret.yaml
  - pull-secret-copy.yaml
  - observabilityMCO.yaml
  - pull-secret-openshift-config-copy.yaml
