apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- example-sno.yaml
- example-3node.yaml
- example-standard.yaml
# - namespace.yaml
# - secret.yaml

## Create the extra-manifest/ directory and copy the desired extra-manifests inside.
## Reference the generated ConfigMap under ClusterInstance.spec.extraManifestRefs.
#
# configMapGenerator:
# - files:
#   - extra-manifest/01-container-mount-ns-and-kubelet-conf-master.yaml
#   - extra-manifest/01-container-mount-ns-and-kubelet-conf-worker.yaml
#   - extra-manifest/01-disk-encryption-pcr-rebind-master.yaml
#   - extra-manifest/01-disk-encryption-pcr-rebind-worker.yaml
#   - extra-manifest/03-sctp-machine-config-master.yaml
#   - extra-manifest/03-sctp-machine-config-worker.yaml
#   - extra-manifest/06-kdump-master.yaml
#   - extra-manifest/06-kdump-worker.yaml
#   - extra-manifest/07-sriov-related-kernel-args-master.yaml
#   - extra-manifest/07-sriov-related-kernel-args-worker.yaml
#   - extra-manifest/08-set-rcu-normal-master.yaml
#   - extra-manifest/08-set-rcu-normal-worker.yaml
#   - extra-manifest/09-openshift-marketplace-ns.yaml
#   - extra-manifest/99-sync-time-once-master.yaml
#   - extra-manifest/99-sync-time-once-worker.yaml
#   - extra-manifest/enable-crun-master.yaml
#   - extra-manifest/enable-crun-worker.yaml
#   name: sno-extra-manifests-configmap
#   namespace: <namespace>
# generatorOptions:
#   disableNameSuffixHash: true
