---
# patching mco StorageClass

- op: replace
  path: /spec/databaseStorage/storageClassName
  value: "ocs-storagecluster-cephfs"  # filesystem StorageClass

- op: replace
  path: /spec/filesystemStorage/storageClassName
  value: "ocs-storagecluster-cephfs"  # filesystem StorageClass

- op: replace
  path: /spec/imageStorage/storageClassName
  value: "ocs-storagecluster-cephfs"  # filesystem StorageClass

  # Configure the osImages urls.
  # When disconnected, the urls should point to a mirrored registry.
- op: replace
  path: "/spec/osImages"
  value:
    - cpuArchitecture: x86_64
      openshiftVersion: "4.19"
      rootFSUrl: https://mirror.example.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.19/latest/rhcos-live-rootfs.x86_64.img
      url: https://mirror.example.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.19/latest/rhcos-live-iso.x86_64.iso
      version: 9.6.20250530-0
    - cpuArchitecture: x86_64
      openshiftVersion: "4.20"
      rootFSUrl: https://mirror.example.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.20/latest/rhcos-live-rootfs.x86_64.img
      url: https://mirror.example.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.20/latest/rhcos-live-iso.x86_64.iso
      version: 9.6.20250530-0
    - cpuArchitecture: x86_64
      openshiftVersion: "4.21"
      rootFSUrl: https://mirror.example.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.21/latest/rhcos-live-rootfs.x86_64.img
      url: https://mirror.example.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.21/latest/rhcos-live-iso.x86_64.iso
      version: 9.6.20251212-1

# when disconnected, the spoke clusters will need to use also a mirrored registry. That could be configured here:
# https://issues.redhat.com/browse/CNF-17835

# In case of connected enviroment we dont need neither to configure
# nor use an internal registry on the spokes. So, uncomment below to remove it:
# - op: remove
#   path: /spec/mirrorRegistryRef
