---
# patching mco StorageClass

- op: replace
  path: /spec/databaseStorage/storageClassName
  value: "ocs-storagecluster-cephfs"  # filesystem StorageClass

- op: replace
  path: /spec/filesystemStorage/storageClassName
  value: "ocs-storagecluster-cephfs"  # filesystem StorageClass

- op: replace
  path: /spec/imageStorage/storageClassName
  value: "ocs-storagecluster-cephfs"  # filesystem StorageClass

  # Configure the osImages urls.
  # When disconnected, the urls should point to a mirrored registry.
- op: replace
  path: "/spec/osImages"
  value:
    - cpuArchitecture: x86_64
      openshiftVersion: "4.16"
      rootFSUrl: https://mirror.example.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.16/latest/rhcos-live-rootfs.x86_64.img
      url: https://mirror.example.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.16/latest/rhcos-live.x86_64.iso
      version: 416.94.202411261619-0
    - cpuArchitecture: "x86_64"
      openshiftVersion: "4.17"
      rootFSUrl: https://mirror.example.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.17/latest/rhcos-live-rootfs.x86_64.img
      url: https://mirror.example.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.17/latest/rhcos-live.x86_64.iso
      version: "417.94.202409121747-0"
    - cpuArchitecture: x86_64
      openshiftVersion: "4.18"
      rootFSUrl: https://mirror.example.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.18/latest/rhcos-live-rootfs.x86_64.img
      url: https://mirror.example.com/pub/openshift-v4/x86_64/dependencies/rhcos/4.18/latest/rhcos-live.x86_64.iso
      version: 418.94.202502100215-0

# when disconnected, the spoke clusters will need to use also a mirrored registry. That could be configured here:
# https://issues.redhat.com/browse/CNF-17835

# In case of connected enviroment we dont need neither to configure
# nor use the registry. So, uncomment below to remove it:
# - op: remove
#   path: /spec/mirrorRegistryRef
